#! /usr/bin/python3

import os
import sys
import time
import random

if len(sys.argv) != 2:
  print(f"{sys.argv[0]}: must be argument <sleep_time>", file=sys.stderr)
  sys.exit(1)
  
sleep_time = int(sys.argv[1])

if sleep_time <= 0:
  print("Minion: Sleep time must be a positive integer.", file=sys.stderr)
  sys.exit(1)

pid = os.getpid()
ppid = os.getppid()

print(f"Minion[{pid}]: created. Parent PID {ppid}.", flush = True)

time.sleep(sleep_time)

exit_status = random.choice([0, 1])

print(f"Child[{pid}]: before terminated. Parent PID {ppid}. Exit status {exit_status}.", flush = True)

os._exit(exit_status)
