#! /usr/bin/python3

import socket
import sys
from datetime import datetime

if len(sys.argv) != 2:
    print("./timeserver <port>")
    sys.exit(1)

port = int(sys.argv[1])
server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

address = '0.0.0.0'
server.bind((address, port))

backlog = 2
server.listen(backlog)

while True:

    client, client_address = server.accept()
    
    datetime_format = "%d.%m.%Y %H:%M"
    current_time = datetime.now().strftime(datetime_format)
    
    client.send(current_time.encode('utf-8'))
    client.close()

